openapi: 3.0.1
info:
  title: Yangguang plugin
  description: A test plugin by Yangguang.
  version: 'v1'
servers:
  - url: http://localhost:3000
paths:
  /api/image:
    post:
      operationId: image
      summary: It takes in a string as the prompt, and outputs a markdown string with the generated image.
      requestBody:
        description: image prompt
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/imageRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/imageResponse'
components:
  schemas:
    imageRequest:
      type: object
      properties:
        prompt:  # the field key
          type: string
          description: Prompt message
    imageResponse:
      type: object
      properties:
        content:  # the field key
          type: string
          description: The ourput result.
