openapi: 3.0.1
info:
  title: Yangguang plugin
  description: A test plugin by Yangguang.
  version: 'v1'
servers:
  - url: http://localhost:3000
paths:
  /api/hello:
    post:
      operationId: hello
      summary: It returns the secret greeting to the user. Send the request with an optional key.
      requestBody:
        description: greeting options
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/helloRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/helloResponse'
components:
  schemas:
    helloResponse:
      type: object
      properties:
        content:  # the field key
          type: string
          description: Greeting content
    helloRequest:
      type: object
      properties:
        key:  # the field key
          type: string
          description: Greeting key
